title: Finn Lattimore
description: My personal blog for notes on math, sailing and random projects.
author: Finn Lattimore
avatar: /finn_headshot.png
email: finnlattimore@gmail.com

skin: daylight

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

markdown: kramdown
kramdown:
  input: GFM   # keep if you already rely on GitHub‑style markdown
  math_engine: mathjax
  math_engine_opts:
    tex: {}

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/

# Jekyll SEO Tag (Optional)
# =========================
# twitter:
#   username: Finn_Lattimore
#   card: summary
# logo: logo.png
# social:
#   name: Finn_Lattimore
#   links:
#     - https://twitter.com/Finn_Lattimore
#     - https://github.com/finnhacks42
# google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
# lang: en
